# Generated by Django 5.2.7 on 2025-10-30 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_address', models.CharField(blank=True, max_length=256, null=True)),
                ('med_blood_group', models.CharField(blank=True, max_length=8, null=True)),
                ('med_allergies', models.TextField(blank=True, null=True)),
                ('med_history', models.TextField(blank=True, null=True)),
                ('med_current_meds', models.TextField(blank=True, null=True)),
                ('emc_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emc_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('emc_relationship', models.CharField(blank=True, max_length=64, null=True)),
                ('vital_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_bp_sys', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_bp_dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vital_height_cm', models.FloatField(blank=True, null=True)),
                ('vital_weight_kg', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
