# Generated by Django 5.2.7 on 2025-11-05 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='vital_bp_dia',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vital_bp_sys',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vital_height_cm',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vital_hr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vital_weight_kg',
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_sys', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('spo2', models.FloatField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
